package viewmodel;

public class Qr {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QR.Id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QR.Integral
     *
     * @mbggenerated
     */
    private Integer integral;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QR.Id
     *
     * @return the value of QR.Id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QR.Id
     *
     * @param id the value for QR.Id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QR.Integral
     *
     * @return the value of QR.Integral
     *
     * @mbggenerated
     */
    public Integer getIntegral() {
        return integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QR.Integral
     *
     * @param integral the value for QR.Integral
     *
     * @mbggenerated
     */
    public void setIntegral(Integer integral) {
        this.integral = integral;
    }
}