package mapper;

import java.util.List;

import viewmodel.Phone;
import viewmodel.PhoneExample;
import org.apache.ibatis.annotations.Param;

public interface PhoneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Phone
     *
     * @mbggenerated
     */
    int countByExample(PhoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Phone
     *
     * @mbggenerated
     */
    int deleteByExample(PhoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Phone
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String number);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Phone
     *
     * @mbggenerated
     */
    int insert(Phone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Phone
     *
     * @mbggenerated
     */
    int insertSelective(Phone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Phone
     *
     * @mbggenerated
     */
    List<Phone> selectByExample(PhoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Phone
     *
     * @mbggenerated
     */
    Phone selectByPrimaryKey(String number);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Phone
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Phone record, @Param("example") PhoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Phone
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Phone record, @Param("example") PhoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Phone
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Phone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Phone
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Phone record);
}