package mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import viewmodel.Qr;
import viewmodel.QrExample;

public interface QrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QR
     *
     * @mbggenerated
     */
    int countByExample(QrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QR
     *
     * @mbggenerated
     */
    int deleteByExample(QrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QR
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QR
     *
     * @mbggenerated
     */
    int insert(Qr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QR
     *
     * @mbggenerated
     */
    int insertSelective(Qr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QR
     *
     * @mbggenerated
     */
    List<Qr> selectByExample(QrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QR
     *
     * @mbggenerated
     */
    Qr selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QR
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Qr record, @Param("example") QrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QR
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Qr record, @Param("example") QrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QR
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Qr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QR
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Qr record);
}