
package mapper;


import viewmodel.Userpermission;

public interface UserpermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserPermission
     *
     * @mbggenerated
     */
    int insert(Userpermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserPermission
     *
     * @mbggenerated
     */
    int insertSelective(Userpermission record);
}